services:
  # Backend API Service
  - type: web
    name: project-hub-api
    env: node
    rootDir: server
    plan: free
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false