services:
  # Backend API Service
  - type: web
    name: project-hub-api
    env: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Static Site
  - type: static_site
    name: project-hub-ui
    env: static
    rootDir: client
    buildCommand: "npm install && ng build"
    publishDir: dist/client/browser
    envVars:
      - key: NG_APP_API_URL
        fromService:
          type: web
          name: project-hub-api
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html